var json_PendidikanMulyaharja_12 = {
"type": "FeatureCollection",
"name": "PendidikanMulyaharja_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OBJECTID": "290", "NIK": null, "NAMA": "MI Azzahra", "ALAMAT": null, "RT": "0", "RW": "0", "KEC": null, "KEL": null, "KLMN": null, "TL": null, "HUB": null, "KAWIN": null, "USIA_24": null, "PEK": null, "PDD": null, "STAT": null, "INDX": null, "BANTU": null, "PHSIL": null, "PLUAR": "0", "STA_BGN": null, "STA_RMH": null, "RODA_2": null, "TANGGUNG": null, "LANTAI": null, "JNS_DIND": null, "KOND_DIN": null, "JNS_ATP": null, "KOND_ATP": null, "MINUM": null, "PR_MINUM": null, "TERANG": null, "DAYA": null, "MASAK": null, "FAS_BAB": null, "KLOSET": null, "TINJA": null, "DISABILITA": null, "SAKIT": null, "JUM_SKLH": null, "N_SKLH": null, "MDL_SKL": null, "BIAYA_SKL": null, "JML_PTS": null, "USAHA": null, "TDK_KRJ": null, "KLG_TG": null, "BLT_STUNT": null, "JALAN": null, "DRAIN": null, "X": 106.79336, "Y": -6.63924, "NO_ID": 0.0, "NO_FORM": 0.0, "KET": "Sekolah", "SURV": null, "FOTO": "A.jpg", "NO_LEGEN": 0.0, "USULAN": null }, "geometry": { "type": "Point", "coordinates": [ 106.793357198000081, -6.639242069999966 ] } },
{ "type": "Feature", "properties": { "OBJECTID": "291", "NIK": null, "NAMA": "TK-SD Al Azhar Syifa Budi", "ALAMAT": null, "RT": "0", "RW": "0", "KEC": null, "KEL": null, "KLMN": null, "TL": null, "HUB": null, "KAWIN": null, "USIA_24": null, "PEK": null, "PDD": null, "STAT": null, "INDX": null, "BANTU": null, "PHSIL": null, "PLUAR": "0", "STA_BGN": null, "STA_RMH": null, "RODA_2": null, "TANGGUNG": null, "LANTAI": null, "JNS_DIND": null, "KOND_DIN": null, "JNS_ATP": null, "KOND_ATP": null, "MINUM": null, "PR_MINUM": null, "TERANG": null, "DAYA": null, "MASAK": null, "FAS_BAB": null, "KLOSET": null, "TINJA": null, "DISABILITA": null, "SAKIT": null, "JUM_SKLH": null, "N_SKLH": null, "MDL_SKL": null, "BIAYA_SKL": null, "JML_PTS": null, "USAHA": null, "TDK_KRJ": null, "KLG_TG": null, "BLT_STUNT": null, "JALAN": null, "DRAIN": null, "X": 106.79192, "Y": -6.63881, "NO_ID": 0.0, "NO_FORM": 0.0, "KET": "Sekolah", "SURV": null, "FOTO": "C.jpg", "NO_LEGEN": 0.0, "USULAN": null }, "geometry": { "type": "Point", "coordinates": [ 106.791919451000069, -6.638808257999926 ] } },
{ "type": "Feature", "properties": { "OBJECTID": "292", "NIK": null, "NAMA": "Pesantren Al-Gifari", "ALAMAT": null, "RT": "0", "RW": "0", "KEC": null, "KEL": null, "KLMN": null, "TL": null, "HUB": null, "KAWIN": null, "USIA_24": null, "PEK": null, "PDD": null, "STAT": null, "INDX": null, "BANTU": null, "PHSIL": null, "PLUAR": "0", "STA_BGN": null, "STA_RMH": null, "RODA_2": null, "TANGGUNG": null, "LANTAI": null, "JNS_DIND": null, "KOND_DIN": null, "JNS_ATP": null, "KOND_ATP": null, "MINUM": null, "PR_MINUM": null, "TERANG": null, "DAYA": null, "MASAK": null, "FAS_BAB": null, "KLOSET": null, "TINJA": null, "DISABILITA": null, "SAKIT": null, "JUM_SKLH": null, "N_SKLH": null, "MDL_SKL": null, "BIAYA_SKL": null, "JML_PTS": null, "USAHA": null, "TDK_KRJ": null, "KLG_TG": null, "BLT_STUNT": null, "JALAN": null, "DRAIN": null, "X": 106.79362, "Y": -6.63828, "NO_ID": 0.0, "NO_FORM": 0.0, "KET": "Sekolah", "SURV": null, "FOTO": "B.jpg", "NO_LEGEN": 0.0, "USULAN": null }, "geometry": { "type": "Point", "coordinates": [ 106.793616962000044, -6.638275851999936 ] } }
]
}
